import { Archivo } from "next/font/google";
import SmoothScrolling from "../components/Smoothscrolling";
import "./globals.css";

const inter = Archivo({ subsets: ["latin"] });

export const metadata = {
  title: "LewdHuTao - Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      <SmoothScrolling />
    </html>
  );
}
